baseURL = "https://nurse.media/"
languageCode = "en-us"
title = "Joel Hans & Nurse Media | Conversion Copywriter | Tucson, Arizona"
googleAnalytics = "UA-9959651-6"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
  name = "Joel Hans"

[permalinks]
  post = "/blog/"

[params]
  favicon = "img/favicon.ico"
  author = "Joel Hans"
  description = "I write nurtured copy that makes businesses grow. Storytelling-driven conversion copywriting for SaaS/tech."
  images = ["site-feature-image.jpg"]
  title = "Joel Hans & Nurse Media | Conversion Copywriter"
  tagline = "I write nurtured copy that makes businesses grow. Storytelling-driven conversion copywriting for SaaS/tech."

# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true