baseURL = "https://nurse.media/"
languageCode = "en-us"
title = "Nurse"
googleAnalytics = "UA-9959651-6"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
  name = "Joel Hans"

[params]
  favicon = "img/favicon.ico"
  author = "Joel Hans"
  description = "It's a harsh world for content out there. Let's nurture yours. Nurse is content for brands that need to grow."
  images = ["site-feature-image.jpg"]
  title = "Nurse - Nurtured content for brands that need to grow"
  tagline = "Nurtured content for brands that need to grow"